config/routes.rb
Rails.application.routes.draw do
  
  
 
  get   '/newjob',  to: 'filejobs#new'
  post  '/filejob',  to: 'filejobs#create'
  get   '/filejob',  to: 'filejobs#index'


  get   '/text',  to: 'classify_results#new'
  post  '/text',  to: 'classify_results#create'

  get '/results', to: 'classify_results#index'

  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
 

 get    '/login',   to: 'sessions#new'
 post   '/login',   to: 'sessions#create'
 delete '/logout',  to: 'sessions#destroy'
  
  resources :classify_results
  resources :users
  resources :filejobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classify.rb
class Classify < ApplicationRecord
end

app/models/classify_result.rb
class ClassifyResult < ApplicationRecord

	#attr_accessor :modelname, :inputtext, :pred, :conf
	validates :inputtext, presence: true, length: { minimum: 5 }
	validates :user_id, presence: true
	belongs_to :user
	before_save  :get_model_name_and_port, :tcp_get_respose, :upcase_inputtext
	attr_accessor :port, :model_id, :inputtext
	
	default_scope -> { order(created_at: :desc) }
    def self.to_csv
    	CSV.generate do |csv|
    		csv << column_names
      		all.each do |classify_result|
        		csv << classify_result.attributes.values_at(*column_names)
            end
        end
    end



private
    
	def tcp_get_respose()
		
		#streamSock = TCPSocket.new( "lpwaidqu04", self.port )  
		#streamSock.puts "12345678901234567890|" +inputtext.upcase
		#outputtext = streamSock.recv(512)
		outputtext = "|1070238717|99.010~"
		lst = outputtext.split("~")[0].split("|")
		self.pred = get_alpha_from_code(lst[1])
		self.conf = lst[2]
 		
 	end

 	def get_model_name_and_port()
 		model_and_port = MlModel.find_by(:id => model_id)
 		self.modelname = model_and_port[:name] 
 		self.port = model_and_port[:port] 
 	end

  	
  	def get_alpha_from_code(code)
  		return NpdIndustry.find_by(:code => code).name
  	end

  	def upcase_inputtext()
  		self.inputtext = inputtext.upcase.delete(' ')
  	end


end

app/models/filejob.rb
class Filejob < ApplicationRecord
	mount_uploader :inpufile, InputfileUploader
    serialize :inpufile, JSON
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    belongs_to :user
end

app/models/ml_model.rb
class MlModel < ApplicationRecord
end

app/models/npd_industry.rb
class NpdIndustry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
									   format: { with: VALID_EMAIL_REGEX },
									   uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
	has_many :classify_results
	has_many :filejobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/classify_results_controller.rb
class ClassifyResultsController < ApplicationController
before_action -> { flash.now[:notice] = flash[:notice].html_safe if flash[:html_safe] && flash[:notice] }
  def new
  	@classify_result ||= ClassifyResult.new
  	#@classify_results = ClassifyResult.paginate(page: params[:page])
  end

  def index
  	@classify_results = current_user.classify_results.paginate(page: params[:page])
  	
    respond_to do |format|
      format.html 
      format.csv { send_data @classify_results.to_csv }
      format.xls 
    end
  end

  def destroy
  	ClassifyResult.find(params[:id]).destroy
  	redirect_to results_url	
  end

  def create 
  	
    @res = current_user.classify_results.build(classify_params)
    
    if not @res.save
      flash[:info] = @res.errors.full_messages
      render 'new'
    else
      redirect_to text_path
    end
    
    
    if not logged_in?
    redirect_to text_path, notice: "
                                  <div><b>Model Name:</b>&nbsp&nbsp&nbsp#{@res[:modelname]}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<b>Input Text:</b>&nbsp&nbsp&nbsp#{@res[:inputtext]}</div>
                                  <div><b>Industry</b>:&nbsp&nbsp&nbsp#{@res[:pred]}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<b>Confidence:</b>&nbsp&nbsp&nbsp#{@res[:conf]}</div>
                                  ",
    flash: { html_safe: true }
    
    end
  end
private
      def classify_params
          params.require(:classify_result).permit(:model_id, :inputtext)
      end

  
  
end

app/controllers/filejobs_controller.rb
class FilejobsController < ApplicationController
  def index
  	@filejobs = Filejob.paginate(page: params[:page])
  	
  end

  def new
  	@filejob = current_user.filejobs.new
  end

  def create
    

    if params[:filejob][:inputfile]
      FileUtils::mkdir_p(Rails.root.join("public/uploads/files"))
 
      ext = File.extname(params[:filejob][:inputfile].original_filename)
      file_name = "#{SecureRandom.urlsafe_base64}#{ext}"
      path = Rails.root.join("public/uploads/files/", file_name)
 
      File.open(path, "wb") {|f| f.write(params[:filejob][:inputfile].read)}
      params[:filejob][:fileuri] = path
      params[:filejob][:origfilename] = params[:filejob][:inputfile].original_filename
      @filejob = current_user.filejobs.new(filejob_params)
  end

    if @filejob.save
       flash.now[:info] = "The Job #{@filejob.name} has been Created."
       
      redirect_to filejob_path
    else
      render "new"
    end
  end

  def destroy
  	Filejobs.find(params[:id]).destroy
  	redirect_to filejob_path
  end

  

  private 
  		def filejob_params

		    params.require(:filejob).permit(:name,:modelname, :origfilename, :fileuri)
		end
end

app/controllers/ml_model_controller.rb
class MlModelController < ApplicationController

 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      #redirect_to user
      redirect_to text_path
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to text_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)    
    if @user.save
      flash[:success] = "Welcome to the DSI Machine Learning Service App!"
      redirect_to text_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classify_results_helper.rb
module ClassifyResultsHelper
end

app/helpers/filejobs_helper.rb
module FilejobsHelper
end

app/helpers/ml_model_helper.rb
module MlModelHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper

	 # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/classify_results/_classify_result.html.erb
  
    <tr>
     
      <td><%= classify_result.modelname %></td>
      <td><%= classify_result.inputtext %></td>
      <td><%= classify_result.pred %></td>
      <td><%= classify_result.conf %></td>
      <td><%= link_to "delete", classify_result, method: :delete,
                                  data: { confirm: "You sure?" } %></td>
      
     </tr>
    

app/views/classify_results/index.html.erb
<h1> Classification Results Review </h1>


 <p>
  Download:
  <%= link_to "CSV", results_path(format: "csv") %> |
  <%= link_to "Excel", results_path(format: "xls") %>
</p>
 <%= will_paginate %>
<table class="table table-striped">

  <thead>
  <tr>
     
      <th scope="col">Model Name</th>
      <th scope="col">Input Text</th>
      <th scope="col">Prediction</th>
      <th scope="col">Confidence(%)</th>
      <th scope="col">Delete</th>
     
    </tr>
     
  </thead> 

  <tbody>
  
  <ul class="classify_results">
    <%= render current_user.classify_results.paginate(page: params[:page]) %>
  </ul>

    </tbody>
   
</table>
<%= will_paginate %>

app/views/classify_results/index.xls.erb
<table border="1">
  <tr>
    <th>ID</th>
    <th>ModelName</th>
    <th>InputText</th>
    <th>Prediction</th>
    <th>Confidence</th>
    <th>Pred Date</th>
  </tr>
  <% @classify_results.each do |res| %>
  <tr>
    <td><%= res.id %></td>
    <td><%= res.modelname %></td>
    <td><%= res.inputtext %></td>
    <td><%= res.pred %></td>
    <td><%= res.conf %></td>
    <td><%= res.created_at %></td>
  </tr>
  <% end %>
</table>

app/views/classify_results/new.html.erb
<h1>Input Text Classifcation</h1>



<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(ClassifyResult.new, url: text_path) do |f| %>
    <%= render 'shared/error_messages' , object: f.object %>

      <%= f.label :inputtext %>
      <%= f.text_field :inputtext, class: 'form-control' %>

      <%= f.label :model_id %>
      <%= f.select :model_id, MlModel.all.pluck(:name,:id), {}, {class: "form-control"} %>
     
      <%= f.submit "Predict", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<% if logged_in? %>
<div class="container-fluid">

<table class="table table-striped">

  <thead>
  <tr>
      
      <th scope="col">Model Name</th>
      <th scope="col">Input Text</th>
      <th scope="col">Prediction</th>
      <th scope="col">Confidence(%)</th>
      
     
    </tr>
     
  </thead> 

  <tbody>
  
      <ul class="classify_results">
    <%= render current_user.classify_results.paginate(page: params[:page])  %>
  </ul>


    </tbody>
   
</table>


</div>
<% end %>

app/views/filejobs/_filejob.html.erb
  
    <tr>
      <td scope="row"><%= filejob.id %></td>
      <td><%= filejob.name %></td>
      <td><%= filejob.modelname %></td>
       <td><%= link_to filejob.origfilename, filejob.fileuri, download: filejob.origfilename %></td>
       
       <td><%= filejob.created_at %></td>
      <td><%= link_to "delete", filejob, method: :delete,
                                  data: { confirm: "You sure?" } %></td>
      
     </tr>
    

app/views/filejobs/create.html.erb
<h1>Filejobs#create</h1>
<p>Find me in app/views/filejobs/create.html.erb</p>

app/views/filejobs/index.html.erb
<h1> Job List </h1>


 
 <%= will_paginate %>
<table class="table table-striped">

  <thead>
  <tr>
      <th scope="col">#</th>
      <th scope="col">Job Name</th>
      <th scope="col">Model Name</th>
      <th scope="col">File Name</th>
      <th scope="col">Created</th>
      <th scope="col">Delete</th>
      
    </tr>
     
  </thead> 

  <tbody>
  
  <ul class="filejob">
    <%= render @filejobs %>
  </ul>

    </tbody>
   
</table>
<%= will_paginate %>

app/views/filejobs/new.html.erb
<% provide(:title, 'FileJobs') %>
<h1>Create Classification job</h1>



<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@filejob, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages' , object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :modelname %>
      <%= f.select :modelname, MlModel.all.pluck(:name,:name), {}, {class: "form-control"} %>

      <%= f.label :inputfile %>
      <%= f.file_field :inputfile %>
      
     
      <%= f.submit "Upload File Job", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    DSI Machine Learning Service
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "DSI Machine Learning Service", text_path, id: "logo" %>
    
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",   text_path %></li>
      <li><%= link_to "Text", text_path %></li>
      <% if logged_in? %>
      
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%="File Jobs"%><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "New File Job", newjob_path %></li>
              <li><%= link_to "Jobs", filejob_path %></li>
              
            </ul>
          </li>
      <% end %>
     
     

              <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%=current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Results", results_path %></li>
             
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
           <li><%= link_to "Sign Up", signup_path %></li> 
        <% end %> 
       
      </ul>
    
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ML Service</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    
     
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
     <%= yield %>
   <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' , object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>